# Generated by Django 4.2.5 on 2023-09-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(Regular)', 'CSE(R)'), ('CSE(HONORS)', 'CSE(H)'), ('CS&IT', 'CSIT')], max_length=100),
        ),
    ]
