# Generated by Django 4.2.5 on 2023-10-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_course_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourseMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
        ),
    ]
